---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ocs.fullname" . }}-basesql
  labels:
    app: {{ template "ocs.name" . }}
    chart: {{ template "ocs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{ (.Files.Glob "sql/*").AsConfig | indent 2 }}
...
