{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocs.fullname" . }}
  labels:
    name: {{ template "ocs.name" . }}
    instance: {{ template "ocs.name" . }}
    chart: {{ template "ocs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    managed-by: helm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  OCS_DB_PASS: {{ .Values.env.OCS_DB_PASS | default (randAlphaNum 32) | b64enc | quote }}
{{ end }}