{{ if .Values.imageCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysecretocs
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig }}
{{ end }}