apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "ocs.fullname" . }}
  labels:
    app: {{ template "ocs.name" . }}
    chart: {{ template "ocs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: ocs
      protocol: TCP
      port: {{ .Values.service.ocsPort }}
      targetPort: ocs
    - name: ssl-ocs
      protocol: TCP
      port: {{ .Values.service.sslOcsPort }}
      targetPort: ssl-ocs
  selector:
    app: {{ template "ocs.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
